// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteApp(index: number): $CancellablePromise<void> {
    return $Call.ByID(1269295324, index);
}

export function GetApps(): $CancellablePromise<$models.App[]> {
    return $Call.ByID(1862096634).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RunApp(index: number): $CancellablePromise<string> {
    return $Call.ByID(1361365550, index);
}

export function SaveApp(app: $models.App): $CancellablePromise<void> {
    return $Call.ByID(3881368978, app);
}

// Private type creation functions
const $$createType0 = $models.App.createFrom;
const $$createType1 = $Create.Array($$createType0);
