// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class App {
    "name": string;
    "icon": string;
    "command": string;
    "args": string[];
    "refresh"?: number;

    /** Creates a new App instance. */
    constructor($$source: Partial<App> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new App instance from a string or object.
     */
    static createFrom($$source: any = {}): App {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        return new App($$parsedSource as Partial<App>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
